### ISSUE TITLE
Sort on timestamp

### ISSUE THREAD

**Issue by chinmaymk** [saleelshetye84/cblProj#3]
instead of just `fileLogLines.reverse();` would be good if we can reverse order on timestamp

**Comment by saleelshetye84** [comment]
In the file `README.design` , I had made the following assumption:

`6. Here the rest endpoint code is assuming that events are time series events and every line of the log file is a seperate event. Basically a time series log file.`

If this is not the case, it means any of the following:

1. Timestamp is present in the events but they are not ordered by time(possibly because the app does not write them sequentially) . In that scenario, it would involve some work to extract the timestamp and then sort it out.
2. Timestamp is not present in the log line, how do we know what the order of the events is?

Am I missing some context here?

**Comment by chinmaymk** [comment]
the assumption does not say any specific ordering, for now lets consider scenario 1/. other scenarios could be handling log file rotation/multiple files etc.

**Comment by saleelshetye84** [comment]
assumption mentioned `time series log file`  https://en.wikipedia.org/wiki/Time_series
So the events are ordered by time.

**Comment by saleelshetye84** [comment]
So let me understand the use cases (outside of the assumption made):
1) Is it that the log file will contain data have time stamps but out of order?
2) Potentially we could also have the time stamp in various formats for every different kind of file?

**Comment by chinmaymk** [comment]
:) in order to return events in reverse time order and satisfy bonus task, its important to have code level understanding of timestamp. i'll leave it up to you as to how generic that mechanism should be.

**Comment by saleelshetye84** [comment]
Added the thoughts on timestamp handling in README.distributed
